// One import point for the whole app:  import { login, searchPatients } from "@/lib/api";
export { api, ApiClientError } from "./client";
export * from "./auth";
export * from "./patients";
export * from "./records";
export * from "./passport-requests";
export * from "./passports";
export * from "./break-glass";
export * from "./admin";
export * from "./audit";